// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/07       [399367]
Creator        : jbertau
Date           : Mon Nov 28 16:59:47 2022
Host           : Linux cmsbuild03.cern.ch 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jbertau/Data/Repositories/PNP_Ana
Training events: 200
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "400" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
a                             a                             a                             a                                                               'F'    [-2.48178482056,3.33943367004]
b                             b                             b                             b                                                               'F'    [-4.09682798386,4.31980609894]
c                             c                             c                             c                                                               'F'    [-5.84607553482,6.66769599915]
d                             d                             d                             d                                                               'F'    [7.0054473877,9.14691162109]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "a", "b", "c", "d" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 2
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 3
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 4
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 5
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 6
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 7
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 8
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 9
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 10
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 11
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 12
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 13
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 14
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 15
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 16
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 17
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 18
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 19
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 20
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 21
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 22
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 23
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 24
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 25
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 26
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 27
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 28
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 29
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 30
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 31
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 32
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 33
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 34
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 35
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 36
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 37
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 38
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 39
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 40
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 41
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 42
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 43
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 44
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 45
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 46
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 47
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 48
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 49
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 50
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 51
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 52
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 53
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 54
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 55
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 56
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 57
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 58
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 59
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 60
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 61
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 62
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 63
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 64
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 65
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 66
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 67
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 68
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 69
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 70
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 71
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 72
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 73
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 74
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 75
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 76
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 77
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 78
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 79
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 80
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 81
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 82
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 83
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 84
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 85
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 86
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 87
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 88
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 89
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 90
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 91
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 92
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 93
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 94
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 95
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 96
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 97
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 98
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 99
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 100
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 101
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 102
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 103
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 104
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 105
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 106
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 107
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 108
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 109
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 110
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 111
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 112
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 113
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 114
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 115
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 116
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 117
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 118
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 119
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 120
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 121
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 122
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 123
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 124
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 125
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 126
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 127
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 128
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 129
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 130
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 131
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 132
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 133
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 134
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 135
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 136
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 137
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 138
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 139
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 140
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 141
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 142
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 143
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 144
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 145
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 146
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 147
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 148
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 149
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 150
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 151
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 152
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 153
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 154
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 155
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 156
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 157
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 158
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 159
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 160
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 161
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 162
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 163
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 164
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 165
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 166
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 167
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 168
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 169
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 170
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 171
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 172
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 173
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 174
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 175
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 176
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 177
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 178
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 179
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 180
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 181
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 182
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 183
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 184
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 185
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 186
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 187
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 188
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 189
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 190
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 191
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 192
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 193
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 194
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 195
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 196
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 197
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 198
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 199
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 200
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 201
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 202
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 203
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 204
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 205
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 206
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 207
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 208
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 209
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 210
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 211
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 212
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 213
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 214
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 215
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 216
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 217
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 218
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 219
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 220
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 221
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 222
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 223
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 224
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 225
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 226
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 227
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 228
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 229
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 230
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 231
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 232
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 233
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 234
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 235
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 236
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 237
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 238
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 239
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 240
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 241
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 242
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 243
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 244
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 245
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 246
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 247
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 248
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 249
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 250
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 251
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 252
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 253
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 254
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 255
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 256
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 257
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 258
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 259
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 260
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 261
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 262
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 263
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 264
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 265
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 266
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 267
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 268
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 269
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 270
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 271
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 272
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 273
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 274
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 275
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 276
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 277
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 278
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 279
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 280
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 281
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 282
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 283
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 284
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 285
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 286
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 287
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 288
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 289
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 290
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 291
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 292
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 293
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 294
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 295
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 296
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 297
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 298
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 299
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 300
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 301
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 302
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 303
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 304
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 305
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 306
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 307
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 308
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 309
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 310
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 311
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 312
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 313
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 314
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 315
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 316
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 317
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 318
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 319
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 320
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 321
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 322
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 323
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 324
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 325
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 326
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 327
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 328
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 329
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 330
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 331
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 332
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 333
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 334
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 335
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 336
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 337
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 338
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 339
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 340
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 341
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 342
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 343
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 344
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 345
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 346
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 347
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 348
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 349
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 350
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 351
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 352
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 353
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 354
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 355
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 356
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 357
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 358
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 359
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 360
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 361
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 362
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 363
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 364
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 365
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 366
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 367
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 368
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 369
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 370
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 371
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 372
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 373
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 374
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 375
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 376
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 377
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 378
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 379
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 380
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 381
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 382
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 383
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 384
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 385
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 386
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 387
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 388
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 389
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 390
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 391
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 392
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 393
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 394
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 395
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 396
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 397
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 398
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
  // itree = 399
  fBoostWeights.push_back(inf);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.112863, 0, 0, 0.5,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
